name: Publish to PyPI

on:
    push:
        tags:
        - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Checkout submodules
          uses: textbook/git-checkout-submodule-action@master
        - name: Setup Python
          uses: actions/setup-python@v1
          with:
              python-version: 3.6
        - name: Build Layers Package
          run: |
              cd mead-baseline/layers
              python setup.py sdist bdist_wheel
              cd ../..
        - name: Publish 8-Mile Package
          if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
          uses: pypa/gh-action-pypi-publish@master
          with:
              user: __token__
              password: ${{ secrets.pypi_password }}
              packages_dir: mead-baseline/layers/dist
        - name: Build Baseline Package
          run: |
              cd mead-baseline
              python setup.py sdist bdist_wheel
              cd ..
        - name: Publish Baseline Package
          if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
          uses: pypa/gh-action-pypi-publish@master
          with:
              user: __token__
              password: ${{ secrets.pypi_password }}
              packages_dir: mead-baseline/dist


